checkin_parking/apps/administration/urls.py
"""
.. module:: checkin_parking.apps.administration.urls
   :synopsis: Checkin Parking Reservation Administration URLs.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from ...urls import administrative_access
from .ajax import purge
from .views import AdminSettingsUpdateView, PurgeView, PDFMapUploadView, BecomeStudentView

app_name = 'administration'

urlpatterns = [
    url(r'^$', login_required(administrative_access(AdminSettingsUpdateView.as_view())), name='settings'),
    url(r'^purge/$', login_required(administrative_access(PurgeView.as_view())), name='purge'),
    url(r'^ajax/run_purge/$', login_required(administrative_access(purge)), name='run_purge'),
    url(r'^maps/$', login_required(administrative_access(PDFMapUploadView.as_view())), name='update_maps'),
    url(r'^become_student/$', login_required(administrative_access(BecomeStudentView.as_view())), name="become_student")
]

checkin_parking/urls.py
"""
.. module:: checkin_parking.urls
   :synopsis: Checkin Parking Reservation URLs.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>
.. moduleauthor:: Thomas Willson <thomas.willson@me.com>

"""

import logging

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static as static_url
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group as group_unregistered
from django.core.exceptions import PermissionDenied
from django.views.decorators.cache import cache_page
from django.views.defaults import permission_denied, page_not_found
from django.views.generic import TemplateView

from django_js_reverse.views import urls_js

from .apps.core.views import handler500
from .settings.base import MAIN_APP_NAME


def permissions_check(test_func, raise_exception=True):
    """
    Decorator for views that checks whether a user has permission to view the
    requested page, redirecting to the log-in page if neccesary.
    If the raise_exception parameter is given the PermissionDenied exception
    is raised.

    :param test_func: A callable test that takes a User object and returns true if the test passes.
    :type test_func: callable
    :param raise_exception: Determines whether or not to throw an exception when permissions test fails.
    :type raise_exception: bool

    """

    def check_perms(user):
        # First check if the user has the permission (even anon users)
        if test_func(user):
            return True
        # In case the 403 handler should be called raise the exception
        if raise_exception:
            raise PermissionDenied
        # As the last resort, show the login form
        return False
    return user_passes_test(check_perms)

administrative_access = permissions_check((lambda user: user.is_admin))
scanner_access = permissions_check((lambda user: user.is_scanner or user.is_admin))

admin.autodiscover()
admin.site.unregister(group_unregistered)

logger = logging.getLogger(__name__)

handler500 = handler500


urlpatterns = [
    url(r'^admin/', TemplateView.as_view(template_name="honeypot.djhtml"), name="honeypot"),  # admin site urls, honeypot
    url(r'^flugzeug/', include(admin.site.urls)),  # admin site urls, masked
    url(r'^reservations/', include(MAIN_APP_NAME + '.apps.reservations.urls')),
    url(r'^zones/', include(MAIN_APP_NAME + '.apps.zones.urls')),
    url(r'^statistics/', include(MAIN_APP_NAME + '.apps.statistics.urls')),
    url(r'^settings/', include(MAIN_APP_NAME + '.apps.administration.urls')),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^', include(MAIN_APP_NAME + '.apps.core.urls')),
]

# Raise errors on purpose
urlpatterns += [
    url(r'^500/$', handler500),
    url(r'^403/$', permission_denied),
    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    urlpatterns += static_url(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkin_parking/apps/administration/models.py
"""
.. module:: checkin_parking.apps.administration.models
   :synopsis: Checkin Parking Reservation Administration Models.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""
from datetime import date, datetime


from django.db.models.base import Model
from django.db.models.fields import PositiveSmallIntegerField, CharField, DateField
from django.utils import timezone

from .managers import AdminSettingsManager
from django.utils.functional import cached_property


class AdminSettings(Model):
    """Administrative settings."""
    APPLICATION_TERMS_CHOICES = [('FA', 'Fall'),
                                 ('WI', 'Winter'),
                                 ('SP', 'Spring'),
                                 ('SU', 'Summer')]

    term_code = PositiveSmallIntegerField(default=2178, verbose_name='Term Code')
    application_term = CharField(default=APPLICATION_TERMS_CHOICES[0][0], choices=APPLICATION_TERMS_CHOICES, max_length=2)
    application_year = PositiveSmallIntegerField(default=datetime.now().year)
    timeslot_length = PositiveSmallIntegerField(default=40, verbose_name='Time Slot Length (in Minutes)')
    reservation_close_day = DateField(default=timezone.now)

    objects = AdminSettingsManager()

    @cached_property
    def reservation_open(self):
        return date.today() <= self.reservation_close_day

    class Meta:
        verbose_name = "Admin Settings"
        verbose_name_plural = "Admin Settings"

checkin_parking/apps/administration/forms.py
"""
.. module:: checkin_parking.apps.administration.forms
   :synopsis: Checkin Parking Reservation Administration Forms.

.. moduleauthor:: Thomas Willson <thomas.willson@me.com>

"""

import os

from clever_selects.forms import ChainedChoicesForm
from clever_selects.form_fields import ChainedModelChoiceField
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse_lazy
from django.forms import Form
from django.forms.fields import FileField, ChoiceField, BooleanField, DateField
from django.forms.models import ModelChoiceField

from rmsconnector.constants import FRESHMAN, TRANSFER, CONTINUING

from ..zones.models import Building, Community


CLASS_LEVELS = [FRESHMAN, TRANSFER, CONTINUING]
CLASS_LEVEL_CHOICES = [(class_level, class_level) for class_level in CLASS_LEVELS]


class PDFMapForm(Form):
    co_pcv_map = FileField(label='Poly Canyon Village Continuing Student Parking Info', required=False)
    trans_pcv_map = FileField(label='Poly Canyon Village Transfer Student Parking Info', required=False)
    pcv_loop = FileField(label='Poly Canyon Village Loop Navigation Info', required=False)
    co_cerro_map = FileField(label='Cerro Vista Continuing Student Parking Info', required=False)
    fresh_trans_cerro_map = FileField(label='Cerro Vista Freshman/Transfer Student Parking Info', required=False)

    def clean(self):
        cleaned_data = super(PDFMapForm, self).clean()
        for filedata in cleaned_data:
            if cleaned_data[filedata]:
                filename = cleaned_data[filedata].name
                ext = os.path.splitext(filename)[1].lower()
                if ext != '.pdf':
                    raise ValidationError("One or more of the files are not PDF documents.")
        return cleaned_data


class BecomeStudentForm(ChainedChoicesForm):
    community = ModelChoiceField(queryset=Community.objects.all(), required=False)
    building = ChainedModelChoiceField('community', reverse_lazy('zones:chained_building'), Building, required=False)
    term_type = ChoiceField(label='Class Level', choices=CLASS_LEVEL_CHOICES)

checkin_parking/apps/administration/views.py
"""
.. module:: checkin_parking.apps.administration.views
   :synopsis: Checkin Parking Reservation Administration Views.

.. moduleauthor:: Thomas Willson <thomas.willson@me.com>

"""

from pathlib import Path

from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, UpdateView

from clever_selects.views import ChainedSelectFormViewMixin

from ...settings.base import MEDIA_ROOT
from ..reservations.models import TimeSlot, ReservationSlot
from .forms import PDFMapForm, BecomeStudentForm
from .models import AdminSettings


class AdminSettingsUpdateView(UpdateView):
    template_name = 'administration/admin_settings.djhtml'
    model = AdminSettings
    fields = ['term_code', 'timeslot_length', 'application_term', 'application_year', 'reservation_close_day']
    success_url = reverse_lazy('administration:settings')

    def get_object(self, queryset=None):
        return AdminSettings.objects.get_settings()

    def form_valid(self, form):
        if any(field in form.changed_data for field in ['term_code', 'timeslot_length']) and (TimeSlot.objects.count() or ReservationSlot.objects.count()):
            form.add_error(None, 'All reservations and time slots must be purged before changing the ' + ' or '.join([field.replace('_', ' ') for field in form.changed_data]) + '.')
            return super(AdminSettingsUpdateView, self).form_invalid(form)

        return super(AdminSettingsUpdateView, self).form_valid(form)


class PurgeView(TemplateView):
    template_name = 'administration/purge.djhtml'

    def get_context_data(self, **kwargs):
        context = super(PurgeView, self).get_context_data(**kwargs)

        context['reservation_count'] = ReservationSlot.objects.count()
        context['timeslot_count'] = TimeSlot.objects.count()

        return context


class PDFMapUploadView(FormView):
    template_name = "administration/map_upload.djhtml"
    form_class = PDFMapForm
    success_url = reverse_lazy('administration:update_maps')

    def form_valid(self, form):
        upload_dir = 'documents'
        upload_full_path = Path(MEDIA_ROOT).joinpath(upload_dir)

        try:
            upload_full_path.mkdir(parents=True)
        except FileExistsError:
            pass

        filenames = {
            'co_pcv_map': 'co_pcv_parking_info.pdf',
            'trans_pcv_map': 'trans_pcv_parking_info.pdf',
            'pcv_loop': 'pcv_loop_nav_info.pdf',
            'co_cerro_map': 'co_cerro_parking_info.pdf',
            'fresh_trans_cerro_map': 'fresh_trans_cerro_parking_info.pdf'
        }

        for key, filename in filenames.items():
            if key in self.request.FILES:
                upload = self.request.FILES[key]
                filedata = b''.join(upload.chunks())

                dest = open(str(upload_full_path.joinpath(filename)), 'wb')
                dest.write(filedata)
                dest.close()

        return super(FormView, self).form_valid(form)


class BecomeStudentView(ChainedSelectFormViewMixin, FormView):
    template_name = "administration/become_student.djhtml"
    form_class = BecomeStudentForm
    success_url = reverse_lazy('administration:become_student')

    def form_valid(self, form):
        user = self.request.user
        user.building = form.cleaned_data['building']
        user.term_type = form.cleaned_data['term_type']
        user.save()

        return super(BecomeStudentView, self).form_valid(form)

checkin_parking/templates/administration/admin_settings.html
{% extends "base.html" %}
{% load staticfiles %}

{% block subtitle %} | Change Settings{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Change Settings</h1>
            <p>Use the following form to change checkin settings.
            <br />
            <strong>You must purge all reservations before changing the term code or time slot length.</strong>
            </p>
            <form method="post" id="create_zone_form">
                <fieldset>
                    <legend>
                        Admin Settings
                    </legend>
                    {{ form.as_p }}
                </fieldset>
                <p>
                    <input type="submit" value="Submit" />
                </p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

checkin_parking/templates/administration/become_student.html
{% extends "base.html" %}

{% block subtitle %} | Become Student{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Become a Student</h1>
            <p>Use the following form to temporarily add student information to your user account allowing you to make, view, and change reservations as 
            if you were a student. Be sure to cancel any reservations you make when you are done testing.</p>
            <form method="post" id="become_student_form">
                <fieldset>
                    <legend>
                        Student Information
                    </legend>
                    {{ form.as_p }}
                </fieldset>
                <p>
                    <input type="submit" value="Submit" />
                </p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

checkin_parking/templates/administration/map_upload.html
{% extends "base.html" %}

{% block subtitle %} | PDF Map Upload{% endblock %}

{% block content %}
	<div id="content">
		<div id="mainLeftFull">
			<h1>PDF Map Upload</h1>
			<p>The following fields may be used to upload informational PDF maps. Links to these maps are displayed when a student views his/her reservation.</p>
			<form method="post" enctype="multipart/form-data" id="zone_text_form">
				{{ form.as_p }}
				<p>
                    <input type="submit" value="Upload" />
                </p>
                {% csrf_token %}
			</form>
		</div>
		<div>
		  <h2>Current PDFs</h2>
            <a href="/media/documents/trans_pcv_parking_info.pdf" target="blank">Poly Canyon Village Transfer Student Parking Information (PDF)</a><br />
            <a href="/media/documents/co_pcv_parking_info.pdf" target="blank">Poly Canyon Village Continuing Student Parking Information (PDF)</a><br />
            <a href="/media/documents/pcv_loop_nav_info.pdf" target="blank">Poly Canyon Village Loop Navigation Information (PDF)</a><br />
            <a href="/media/documents/fresh_trans_cerro_parking_info.pdf" target="blank">Cerro Vista Freshman/Transfer Student Parking Information (PDF)</a><br />
            <a href="/media/documents/co_cerro_parking_info.pdf" target="blank">Cerro Vista Continuing Student Parking Information (PDF)</a><br />
		</div>
	</div>
{% endblock %}

checkin_parking/templates/administration/purge.html
{% extends "base.html" %}
{% load staticfiles %}

{% block subtitle %} | Pure Reservations{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Purge Reservations</h1>
            <p>This allows you to purge all {{ reservation_count }} reservations and {{ timeslot_count }} time slots from the database.
            <br /><br />
            <strong>USE THIS WITH CARE. THIS OPERATION CANNOT BE UNDONE.</strong>
            </p>
            <button id="purge_button" onclick="purge();" style="padding 3px 3px;"><strong style="color: red; font-size: 150%;">Purge!</strong></button>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'js/jquery.blockUI.js' %}"></script>
<script type="text/javascript">
    function purge() {
        if (confirm('Are you sure you want to delete all reservations and time slots? THIS CANNOT BE UNDONE!')) {
            $.blockUI({message: '<h1 style="padding 6px 6px; margin-bottom: 0px;">Purging the database. Please wait...</h1>'});
            ajaxPost("{% url 'administration:run_purge' %}", {'confirmation': true}, function(response){
                $.unblockUI()
                alert(response['reservation_count'].toString() + ' Reservations Deleted & ' + response['timeslot_count'] + ' Timeslots Deleted.');

            });
        }
    };
</script>
{% endblock %}