checkin_parking/apps/reservations/urls.py
"""
.. module:: checkin_parking.apps.reservations.urls
   :synopsis: Checkin Parking Reservation Reservations URLs.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from ...urls import administrative_access, scanner_access
from ..core.views import IndexView
from .ajax import reserve_slot, cancel_reservation, delete_timeslot
from .views import GenerateReservationSlotsView, ParkingPassPDFView, ParkingPassVerificationView, ReserveView, ViewReservationView, ChangeReservationView, TimeSlotListView


app_name = 'reservations'

urlpatterns = [
    url(r'^slots/generate/$', login_required(administrative_access(GenerateReservationSlotsView.as_view())), name='generate_reservation_slots'),

    url(r'^slots/list/$', login_required(administrative_access(TimeSlotListView.as_view())), name='list_time_slots'),
    url(r'^slots/(?P<id>\d+)/$', login_required(administrative_access(IndexView.as_view())), name='update_time_slot'),  # What?
    url(r'^ajax/delete_time_slot/$', login_required(administrative_access(delete_timeslot)), name='delete_time_slot'),

    url(r'^reserve/$', login_required(ReserveView.as_view()), name='reserve'),
    url(r'^ajax/reserve_slot/$', login_required(reserve_slot), name='reserve_slot'),
    url(r'^view/$', login_required(ViewReservationView.as_view()), name='view_reservation'),
    url(r'^change/$', login_required(ChangeReservationView.as_view()), name='change_reservation'),
    url(r'^ajax/cancel/$', login_required(cancel_reservation), name='cancel_reservation'),

    url(r'^parking-pass/generate/$', login_required(ParkingPassPDFView.as_view()), name='generate_parking_pass'),
    url(r'^parking-pass/verify/(?P<reservation_id>\d+)/(?P<user_id>\d+)/$', login_required(scanner_access(ParkingPassVerificationView.as_view())), name='verify_parking_pass'),
]

checkin_parking/urls.py
"""
.. module:: checkin_parking.urls
   :synopsis: Checkin Parking Reservation URLs.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>
.. moduleauthor:: Thomas Willson <thomas.willson@me.com>

"""

import logging

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static as static_url
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group as group_unregistered
from django.core.exceptions import PermissionDenied
from django.views.decorators.cache import cache_page
from django.views.defaults import permission_denied, page_not_found
from django.views.generic import TemplateView

from django_js_reverse.views import urls_js

from .apps.core.views import handler500
from .settings.base import MAIN_APP_NAME


def permissions_check(test_func, raise_exception=True):
    """
    Decorator for views that checks whether a user has permission to view the
    requested page, redirecting to the log-in page if neccesary.
    If the raise_exception parameter is given the PermissionDenied exception
    is raised.

    :param test_func: A callable test that takes a User object and returns true if the test passes.
    :type test_func: callable
    :param raise_exception: Determines whether or not to throw an exception when permissions test fails.
    :type raise_exception: bool

    """

    def check_perms(user):
        # First check if the user has the permission (even anon users)
        if test_func(user):
            return True
        # In case the 403 handler should be called raise the exception
        if raise_exception:
            raise PermissionDenied
        # As the last resort, show the login form
        return False
    return user_passes_test(check_perms)

administrative_access = permissions_check((lambda user: user.is_admin))
scanner_access = permissions_check((lambda user: user.is_scanner or user.is_admin))

admin.autodiscover()
admin.site.unregister(group_unregistered)

logger = logging.getLogger(__name__)

handler500 = handler500


urlpatterns = [
    url(r'^admin/', TemplateView.as_view(template_name="honeypot.djhtml"), name="honeypot"),  # admin site urls, honeypot
    url(r'^flugzeug/', include(admin.site.urls)),  # admin site urls, masked
    url(r'^reservations/', include(MAIN_APP_NAME + '.apps.reservations.urls')),
    url(r'^zones/', include(MAIN_APP_NAME + '.apps.zones.urls')),
    url(r'^statistics/', include(MAIN_APP_NAME + '.apps.statistics.urls')),
    url(r'^settings/', include(MAIN_APP_NAME + '.apps.administration.urls')),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^', include(MAIN_APP_NAME + '.apps.core.urls')),
]

# Raise errors on purpose
urlpatterns += [
    url(r'^500/$', handler500),
    url(r'^403/$', permission_denied),
    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    urlpatterns += static_url(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkin_parking/apps/reservations/models.py
"""
.. module:: checkin_parking.checkin_sessions.models
   :synopsis: Checkin Parking Reservation Models.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from datetime import datetime, timedelta

from django.conf import settings
from django.db.models.base import Model
from django.db.models.deletion import SET_NULL
from django.db.models.fields import CharField, DateField, TimeField, PositiveSmallIntegerField, BooleanField, DateTimeField, NullBooleanField
from django.db.models.fields.related import ForeignKey, OneToOneField
from django.utils.functional import cached_property

from rmsconnector.constants import FRESHMAN, TRANSFER, CONTINUING

from ..administration.models import AdminSettings
from ..core.managers import DefaultRelatedManager
from ..core.models import CheckinParkingUser
from ..zones.models import Zone


CLASS_LEVELS = [FRESHMAN, TRANSFER, CONTINUING,
                FRESHMAN + '/' + TRANSFER, FRESHMAN + '/' + CONTINUING, TRANSFER + '/' + CONTINUING,
                FRESHMAN + '/' + TRANSFER + '/' + CONTINUING]
CLASS_LEVEL_CHOICES = [(class_level, class_level) for class_level in CLASS_LEVELS]


class TimeSlot(Model):
    """A slot of time."""

    date = DateField(verbose_name="Date")
    time = TimeField(verbose_name="Time")
    term_code = PositiveSmallIntegerField(verbose_name="Term Code")

    @cached_property
    def datetime(self):
        combined = datetime.combine(self.date, self.time)
        return datetime.strftime(combined, settings.PYTHON_DATETIME_FORMAT)

    @cached_property
    def datetime_obj(self):
        combined = datetime.combine(self.date, self.time)
        return combined

    @cached_property
    def end_time(self):
        return (datetime.combine(datetime.today(), self.time) + timedelta(minutes=AdminSettings.objects.get_settings().timeslot_length)).time()

    @cached_property
    def end_datetime_obj(self):
        combined = datetime.combine(self.date, self.time)
        combined += timedelta(minutes=AdminSettings.objects.get_settings().timeslot_length)
        return combined

    def __str__(self):
        return self.datetime + " (" + str(self.term_code) + ")"


class ReservationSlot(Model):
    """ A parking session."""

    class_level = CharField(max_length=30, default=CLASS_LEVELS.index(FRESHMAN + '/' + TRANSFER + '/' + CONTINUING), choices=CLASS_LEVEL_CHOICES, verbose_name="Class Level")
    assisted = BooleanField(default=False, verbose_name="assisted?")
    timeslot = ForeignKey(TimeSlot, related_name="reservationslots", verbose_name="Time Slot")
    zone = ForeignKey(Zone, related_name="reservationslots", verbose_name="Zone")
    resident = OneToOneField(CheckinParkingUser, null=True, blank=True, related_name="reservationslot", verbose_name="Resident", on_delete=SET_NULL)

    objects = DefaultRelatedManager(select_related=["timeslot", "zone", "resident"])

    last_scanned = DateTimeField(null=True, blank=True)
    last_scanned_on_time = NullBooleanField()

    def __str__(self):
        return str(self.timeslot) + " - " + str(self.zone) + ": " + (str(self.resident) if self.resident else "Open")

checkin_parking/apps/reservations/views.py
"""
.. module:: checkin_parking.apps.reservations.views
   :synopsis: Checkin Parking Reservation Reservation Views.

.. moduleauthor:: Thomas Willson <thomas.willson@me.com>

"""

from datetime import date as datetime_date, datetime, timedelta

from django.core.exceptions import FieldError, ValidationError
from django.core.urlresolvers import reverse_lazy
from django.db import transaction
from django.http.response import HttpResponse, HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from checkin_parking.apps.reservations.utils import generate_verification_url

from ..administration.models import AdminSettings
from .forms import GenerateReservationsForm
from .models import TimeSlot, ReservationSlot
from .utils import generate_pdf_file


class GenerateReservationSlotsView(FormView):
    template_name = "reservations/generate_reservation_slots.djhtml"
    form_class = GenerateReservationsForm
    success_url = reverse_lazy('reservations:list_time_slots')

    def form_valid(self, form):
        date = form.cleaned_data["date"]
        start_time = form.cleaned_data["start_time"]
        end_time = form.cleaned_data["end_time"]
        class_level = form.cleaned_data["class_level"]
        assisted = form.cleaned_data["assisted"]
        zones = form.cleaned_data["zones"]

        admin_settings = AdminSettings.objects.get_settings()
        end_datetime = datetime.combine(datetime_date.today(), end_time)

        delta = end_datetime - datetime.combine(datetime_date.today(), start_time)

        with transaction.atomic():
            # Split the time span into admin_settings.timeslot_length chunks
            while delta.total_seconds() > 0:
                timeslot = TimeSlot()
                timeslot.date = date
                timeslot.time = start_time
                timeslot.term_code = admin_settings.term_code
                timeslot.save()

                # For each zone, create zone.capacity reservation slots
                for zone in zones:
                    for index in range(zone.capacity):
                        reservationslot = ReservationSlot()
                        reservationslot.class_level = class_level
                        reservationslot.assisted = assisted
                        reservationslot.timeslot = timeslot
                        reservationslot.zone = zone
                        reservationslot.save()

                start_time = (datetime.combine(datetime_date.today(), start_time) + timedelta(minutes=admin_settings.timeslot_length)).time()
                delta = end_datetime - datetime.combine(datetime_date.today(), start_time)

        return super(GenerateReservationSlotsView, self).form_valid(form)


class TimeSlotListView(ListView):
    template_name = "reservations/list_time_slots.djhtml"
    model = TimeSlot


class ParkingPassVerificationView(TemplateView):
    template_name = 'reservations/parking_pass_verification.djhtml'

    def get_context_data(self, **kwargs):
        context = super(ParkingPassVerificationView, self).get_context_data(**kwargs)

        reservation_id = kwargs['reservation_id']
        user_id = int(kwargs['user_id'])
        valid_pass = True
        context['scanned_on_time'] = False
        context['scanned_early'] = False
        context['num_minutes_early'] = 0
        
        try:
            reservation_slot = ReservationSlot.objects.get(id=reservation_id)

            if not reservation_slot.resident or reservation_slot.resident.id != user_id:
                valid_pass = False
        except ReservationSlot.DoesNotExist:
            valid_pass = False

        context['parking_pass_valid'] = valid_pass

        if valid_pass:
            reservation_slot.last_scanned = datetime.now()
            timeslot = reservation_slot.timeslot
            if timeslot.datetime_obj <= datetime.now() and timeslot.end_datetime_obj >= datetime.now():
                reservation_slot.last_scanned_on_time = True
                context['scanned_on_time'] = True
            else:
                reservation_slot.last_scanned_on_time = False
                if timeslot.datetime_obj > datetime.now():
                    context['scanned_early'] = True
                    time_delta = timeslot.datetime_obj - datetime.now()
                    context['num_minutes_early'] = int(round(time_delta.seconds / 60))
            reservation_slot.save()

        return context


class ParkingPassPDFView(TemplateView):
    template_name = 'reservations/parking_pass.rml'

    def get_context_data(self, **kwargs):
        context = super(ParkingPassPDFView, self).get_context_data(**kwargs)

        try:
            reservation_slot = ReservationSlot.objects.get(id=self.request.user.reservationslot.id)
        except ReservationSlot.DoesNotExist:
            raise ValidationError('You do not have a parking reservation on file. If you believe this is in error, call ResNet at (805) 756-5600.')

        context['reservation_slot'] = reservation_slot

        return context

    def render_to_response(self, context, **response_kwargs):
        pdf_data = generate_pdf_file(context['reservation_slot'], generate_verification_url(context['reservation_slot'], self.request))

        response = HttpResponse()
        response['Content-Type'] = 'application/pdf'
        response['Content-Disposition'] = 'filename=parkingpass.pdf'

        response.write(pdf_data)

        return response


class ReserveView(ListView):
    template_name = 'reservations/reserve.djhtml'
    model = TimeSlot

    def get_queryset(self, **kwargs):
        building = self.request.user.building
        term_type = self.request.user.term_type

        if not term_type:
            raise FieldError('Could not retrieve class level. Please call ResNet at (805) 756-5600.')

        base_queryset = TimeSlot.objects.filter(reservationslots__resident=None, reservationslots__class_level__contains=term_type)

        # Show all open zone slots
        queryset = base_queryset.filter(reservationslots__zone__buildings__name__contains="All")

        # Show building specific slots as well
        if building:
            queryset = queryset | base_queryset.filter(reservationslots__zone__buildings=building)

        queryset = queryset.order_by('date', 'time')

        if 'change_reservation' in kwargs:
            return queryset.exclude(reservationslots__resident=self.request.user).distinct()
        else:
            return queryset.distinct()

    def render_to_response(self, context, **response_kwargs):
        if 'change_reservation' not in context:
            try:
                ReservationSlot.objects.get(id=self.request.user.reservationslot.id)
                return HttpResponseRedirect(reverse_lazy('reservations:view_reservation'))
            except:
                pass

        return super(ReserveView, self).render_to_response(context, **response_kwargs)


class ViewReservationView(DetailView):
    template_name = 'reservations/reservation_view.djhtml'
    model = ReservationSlot

    def get_object(self, queryset=None):
        try:
            reservation_slot = ReservationSlot.objects.get(id=self.request.user.reservationslot.id)
        except ReservationSlot.DoesNotExist:
            raise ValidationError('You do not have a parking reservation on file. If you believe this is in error, call ResNet at (805) 756-5600.')

        return reservation_slot


class ChangeReservationView(ReserveView):

    def get_context_data(self, **kwargs):
        context = super(ChangeReservationView, self).get_context_data(**kwargs)
        context['change_reservation'] = True
        return context

    def get_queryset(self, **kwargs):
        kwargs['change_reservation'] = True
        return super(ChangeReservationView, self).get_queryset(**kwargs)

checkin_parking/templates/reservations/generate_reservation_slots.html
{% extends "base.html" %}

{% load staticfiles %}

{% block subtitle %} | Generate Reservation Slots{% endblock %}

{% block meta %}
{{ block.super }}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.css" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/jqueryui/jqueryui-1.8.22.cp.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Generate Reservation Slots</h1>
            <p>Use the following form to generate reservation slots. For each {{ timeslot_length }} minute chunk of the time range you enter below and for each zone you select, a reservation slot will be generated based on the capacity of each zone.</p>
            <form method="post" id="create_zone_form">
                <fieldset>
                    <legend>
                        Generate Reservation Slots
                    </legend>
                    {{ form.as_p }}
                </fieldset>
                <p>
                    <input type="submit" value="Submit" />
                </p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
{{ block.super }}
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#id_date").datepicker({
                minDate: 0,
                dateFormat: 'yy-mm-dd',
            });
            $("#id_start_time, #id_end_time").timepicker({
                timeFormat: 'HH:mm',
                stepHour: 1,
                stepMinute: 10,
            });
        });
    </script>
{% endblock %}

checkin_parking/templates/reservations/list_time_slots.html
{% extends "base.html" %}
{% load staticfiles %}

{% block subtitle %} | Zones{% endblock %}


{% block content%}
<div id="content">
    <div id="mainLeftFull">
        <h1>
            View Time Slots
        </h1>
        <table border="1" class="table_directory">
            <tbody>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Zone Name</th>
                    <th scope="col">Zone Cap.</th>
                    <th scope="col">Class Level</th>
                    <th scope="col">Delete</th>
                </tr>
                {% for timeslot in timeslot_list %}
                <tr id="timeslot_{{ timeslot.id }}">
                    <td>{{ timeslot.date}}</td>
                    <td>{{ timeslot.time}}</td>
                    <td>{{ timeslot.end_time }}</td>
                    <td>{{ timeslot.reservationslots.first.zone.name }}</td>
                    <td>{{ timeslot.reservationslots.first.zone.capacity }}</td>
                    <td>{{ timeslot.reservationslots.first.class_level }}</td>
                    <td onclick="delete_timeslot('{{timeslot.id}}');"><a class="delete">Delete</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">There are no time slots in the database.</td>
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block extra_script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/jquery.blockUI.js' %}"></script>
<script type="text/javascript">
    function delete_timeslot(timeslot_id) {
        if (confirm('Would you like to delete this timeslot?')) {
            $.blockUI({message: '<h1 style="padding: 6px 6px; margin-bottom: 0px;">Deleting the timeslot. Please wait...</h1>'});
            ajaxPost("{% url 'reservations:delete_time_slot' %}", {'timeslot_id': timeslot_id}, function(response) {
                $.unblockUI();
                if (response['success']) {
                    $('#timeslot_' + timeslot_id).remove();
                }
                else {
                    if (response['reservation_count']) {
                        alert('Could not delete this time slot because there are ' + response['reservation_count'].toString() + ' reservations attached to it.');
                    }
                    else { 
                        alert('An error occurred when trying to delete this time slot. Please try again later.');
                    }
                }
            });
            
        }
    };
</script>
{% endblock %}

checkin_parking/templates/reservations/parking_pass_verification.html
{% extends "base.html" %}

{% block content %}
	<div id="content">
	    <div id="mainLeftFull">
	        <h1>Parking Pass Verification</h1>
            {% if parking_pass_valid %}
                <h2 style="font-size: 250%;">VALID</h2>
            {% else %}
                <h2 style="color: red; font-size: 250%;">INVALID</h2>
            {% endif %}
	    </div>
	</div>
{% endblock %}

checkin_parking/templates/reservations/reservation_view.html
{% extends "base.html" %}
{% load staticfiles %}

{% block subtitle %} | Zones{% endblock %}


{% block content%}
<div id="content">
    <div id="mainLeftFull">
        <h1>
            View Reservation
        </h1>
        <h3>
            Reservation Details
        </h3>
        <table border="1" class="table_directory">
            <tbody>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Zone</th>
                    {% if reservation_open %}
                        <th scope="col">Cancel</th>
                    {% endif %}
                </tr>
                <tr>
                    <td>{{ reservationslot.timeslot.date }}</td>
                    <td>{{ reservationslot.timeslot.time }}</td>
                    <td>{{ reservationslot.timeslot.end_time }}</td>
                    <td>{{ reservationslot.zone.name }}</td>
                    {% if reservation_open %}
                    <td onclick="cancel_reservation();"><a class="delete">Cancel</a></td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
        
            <p>The links below are documents that contain your move-in date, time and location as well as instructions and a detailed map with directions to your move-in location. You must print out the parking pass and display it on your vehicle when you enter the 40 minute unloading zones.</p>
            <br /><h3>Information & Parking Pass</h3>
            <p>
            {% if reservationslot.zone.community.name == 'Poly Canyon Village' %}
                {% if not 'Continuing' in reservationslot.class_level %}
                <a href="/media/documents/trans_pcv_parking_info.pdf" target="blank">Poly Canyon Village Transfer Student Parking Information (PDF)</a><br />
                {% else %}
                <a href="/media/documents/co_pcv_parking_info.pdf" target="blank">Poly Canyon Village Continuing Student Parking Information (PDF)</a><br />
                {% endif %}
                <a href="/media/documents/pcv_loop_nav_info.pdf" target="blank">Poly Canyon Village Loop Navigation Information (PDF)</a><br />
            {% endif %}
            {% if reservationslot.zone.community.name  == 'Cerro Vista' %}
                {% if not 'Continuing' in reservationslot.class_level %}
                <a href="/media/documents/fresh_trans_cerro_parking_info.pdf" target="blank">Cerro Vista Freshman/Transfer Student Parking Information (PDF)</a><br />
                {% else %}
                <a href="/media/documents/co_cerro_parking_info.pdf" target="blank">Cerro Vista Continuing Student Parking Information (PDF)</a><br />
                {% endif %}
            {% endif %}
            <br />
            <a href="{% url 'reservations:generate_parking_pass' %}">Move-in Registration Parking Pass (PDF)</a>
            </p>
    </div>
</div>
{% endblock %}

{% if reservation_open %}
{% block extra_script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/jquery.blockUI.js' %}"></script>
<script type="text/javascript">
    function cancel_reservation() {
        if (confirm('Would you like to cancel your reservation?')) {
            $.blockUI({message: '<h1 style="padding 6px 6px; margin-bottom: 0px;">Canceling your reservation. Please wait...</h1>'});
            ajaxPost("{% url 'reservations:cancel_reservation' %}", {}, function(response) {
                if (response['success']) {
                    window.open("{% url 'reservations:reserve' %}", '_self');
                }
                else {
                    $.unblockUI();
                    alert('An error occurred when trying to cancel your reservation. Please try again later.');
                }
            });
            
        }
    };
</script>
{% endblock %}
{% endif %}

checkin_parking/templates/reservations/reserve.html
{% extends "base.html" %}
{% load staticfiles %}

{% block subtitle %} | Zones{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>{% if change_reservation %}Change Reservation{% else %}Available Slots{% endif %}</h1>
            <p>Please pick one of the below available times.</p>
            <table border="1" class="table_directory">
                <tbody>
                    <tr>
                        <th>Date</th>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th>Reserve</th>
                    </tr>
                    {% for slot in timeslot_list %}
                    <tr id="slot_{{ slot.id }}" onclick="reserve_slot({{ slot.id }}, '{{ slot.time }}', '{{ slot.date }}');" style="cursor: pointer;">
                        <td>{{ slot.date }}</td>
                        <td>{{ slot.time }}</td>
                        <td>{{ slot.end_time }}</td>
                        <td><a class="update">Reserve</a></td>
                    </tr>
                    {% empty %}
                        {% if error_text %}
                        <tr>
                            <td colspan="4">{{error_text}}</td>
                        </tr>
                        {% else %}
                        <tr>
                           <td colspan="4">There are no available timeslots.</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/jquery.blockUI.js' %}"></script>
<script type="text/javascript">
    function reserve_slot(slot_id, slot_time, slot_date) {
        if (confirm('Would you like to reserve the slot starting at ' + slot_time + ' on ' + slot_date + '?')) {
            $.blockUI({message: '<h1 style="padding: 6px 6px; margin-bottom: 0px;">Reserving your slot. Please wait...</h1>'});
            ajaxPost("{% url 'reservations:reserve_slot' %}", {'slot_id': slot_id{% if change_reservation %}, 'change_reservation': true{% endif %}}, function(response) {
                if (response['success']) {
                    window.open("{% url 'reservations:view_reservation' %}", '_self');
                }
                else {
                    $('#slot_' + slot_id).remove();
                    $.unblockUI();
                    alert('Sorry, that slot is no longer available. Please select another slot.');
                }
            });
            
        }
    };
</script>
{% endblock %}