checkin_parking/apps/zones/urls.py
"""
.. module:: checkin_parking.apps.zones.urls
   :synopsis: Checkin Parking Reservation Zone URLs.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from ...urls import administrative_access
from .ajax import BuildingChainedAjaxView, delete_zone
from .views import ZoneListView, ZoneCreateView, ZoneUpdateView

app_name = 'zones'

urlpatterns = [
    url(r'^list/$', login_required(administrative_access(ZoneListView.as_view())), name='list_zones'),
    url(r'^create/$', login_required(administrative_access(ZoneCreateView.as_view())), name='create_zone'),
    url(r'^update/(?P<id>\d+)/$', login_required(administrative_access(ZoneUpdateView.as_view())), name='update_zone'),
    url(r'^ajax/delete/$', login_required(administrative_access(delete_zone)), name='delete_zone'),
    url(r'^ajax/update_buildings/$', login_required(BuildingChainedAjaxView.as_view()), name='chained_building'),
]

checkin_parking/checkin_parking/urls.py
"""
.. module:: checkin_parking.urls
   :synopsis: Checkin Parking Reservation URLs.

.. moduleauthor:: Alex Kavanaugh <kavanaugh.development@outlook.com>
.. moduleauthor:: RJ Almada <almada.dev@gmail.com>

"""

import logging

from django.conf import settings
from django.conf.urls.static import static as static_url
from django.conf.urls import patterns, include, url
from django.core.exceptions import PermissionDenied
from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.views.generic import RedirectView

from .settings.base import ral_manager_access_test
from .core.views import IndexView, LoginView, logout
from .zones.views import ZoneCreateView
from .zones.ajax import update_building


def permissions_check(test_func, raise_exception=True):
    """
    Decorator for views that checks whether a user has permission to view the
    requested page, redirecting to the log-in page if neccesary.
    If the raise_exception parameter is given the PermissionDenied exception
    is raised.

    :param test_func: A callable test that takes a User object and returns true if the test passes.
    :type test_func: callable
    :param raise_exception: Determines whether or not to throw an exception when permissions test fails.
    :type raise_exception: bool

    """

    def check_perms(user):
        # First check if the user has the permission (even anon users)
        if test_func(user):
            return True
        # In case the 403 handler should be called raise the exception
        if raise_exception:
            raise PermissionDenied
        # As the last resort, show the login form
        return False
    return user_passes_test(check_perms)

ral_manager_access = permissions_check(ral_manager_access_test)

admin.autodiscover()

logger = logging.getLogger(__name__)


# Core
urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^favicon\.ico$', RedirectView.as_view(url=static('images/icons/favicon.ico')), name='favicon'),
    url(r'^flugzeug/', include(admin.site.urls)),  # admin site urls, masked
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),
)

# Sessions
urlpatterns += patterns('',
    url(r'^sessions/list/$', login_required(ral_manager_access(IndexView.as_view())), name='list_sessions'),
    url(r'^sessions/create/$', login_required(ral_manager_access(IndexView.as_view())), name='create_sessions'),
    url(r'^sessions/(?P<id>\d+)/$', login_required(ral_manager_access(IndexView.as_view())), name='edit_session'),
    url(r'^sessions/(?P<id>\d+)/delete/$', login_required(ral_manager_access(IndexView.as_view())), name='delete_session'),
    url(r'^sessions/reservation/reserve/$', login_required(IndexView.as_view()), name='reserve_session'),
    url(r'^sessions/reservation/detail/$', login_required(IndexView.as_view()), name='view_reservation'),
    url(r'^sessions/reservation/change/$', login_required(IndexView.as_view()), name='change_reservation'),
    url(r'^sessions/reservation/cancel/$', login_required(IndexView.as_view()), name='cancel_reservation'),
    url(r'^sessions/update/$', login_required(IndexView.as_view()), name='update_sessions'),
)

# Zones
urlpatterns += patterns('',
    url(r'^zones/list/$', login_required(ral_manager_access(IndexView.as_view())), name='list_zones'),
    url(r'^zones/create/$', login_required(ral_manager_access(ZoneCreateView.as_view())), name='create_zone'),
    url(r'^zones/(?P<id>\d+)/$', login_required(ral_manager_access(IndexView.as_view())), name='edit_zone'),
    url(r'^zones/(?P<id>\d+)/delete/$', login_required(ral_manager_access(IndexView.as_view())), name='delete_zone'),
    url(r'^zones/ajax/update_building/$', login_required(update_building), name='ajax_update_building'),
)

# PDFs
urlpatterns += patterns('',
    url(r'^pdfs/maps/list/$', login_required(ral_manager_access(IndexView.as_view())), name='list_maps'),
    url(r'^pdfs/parking_pass/generate/$', login_required(IndexView.as_view()), name='generate_parking_pass'),
)

# Residents
urlpatterns += patterns('',
    url(r'^residents/lookup/$', login_required(ral_manager_access(IndexView.as_view())), name='lookup_residents'),
)

# Statistics
urlpatterns += patterns('',
    url(r'^statistics/$', login_required(ral_manager_access(IndexView.as_view())), name='statistics'),
)

# Administration
urlpatterns += patterns('',
    url(r'^admin/settings/$', login_required(ral_manager_access(IndexView.as_view())), name='settings'),
    url(r'^admin/purge/$', login_required(ral_manager_access(IndexView.as_view())), name='purge'),
)

if settings.DEBUG:
    urlpatterns += static_url(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkin_parking/urls.py
"""
.. module:: checkin_parking.urls
   :synopsis: Checkin Parking Reservation URLs.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>
.. moduleauthor:: Thomas Willson <thomas.willson@me.com>

"""

import logging

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static as static_url
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group as group_unregistered
from django.core.exceptions import PermissionDenied
from django.views.decorators.cache import cache_page
from django.views.defaults import permission_denied, page_not_found
from django.views.generic import TemplateView

from django_js_reverse.views import urls_js

from .apps.core.views import handler500
from .settings.base import MAIN_APP_NAME


def permissions_check(test_func, raise_exception=True):
    """
    Decorator for views that checks whether a user has permission to view the
    requested page, redirecting to the log-in page if neccesary.
    If the raise_exception parameter is given the PermissionDenied exception
    is raised.

    :param test_func: A callable test that takes a User object and returns true if the test passes.
    :type test_func: callable
    :param raise_exception: Determines whether or not to throw an exception when permissions test fails.
    :type raise_exception: bool

    """

    def check_perms(user):
        # First check if the user has the permission (even anon users)
        if test_func(user):
            return True
        # In case the 403 handler should be called raise the exception
        if raise_exception:
            raise PermissionDenied
        # As the last resort, show the login form
        return False
    return user_passes_test(check_perms)

administrative_access = permissions_check((lambda user: user.is_admin))
scanner_access = permissions_check((lambda user: user.is_scanner or user.is_admin))

admin.autodiscover()
admin.site.unregister(group_unregistered)

logger = logging.getLogger(__name__)

handler500 = handler500


urlpatterns = [
    url(r'^admin/', TemplateView.as_view(template_name="honeypot.djhtml"), name="honeypot"),  # admin site urls, honeypot
    url(r'^flugzeug/', include(admin.site.urls)),  # admin site urls, masked
    url(r'^reservations/', include(MAIN_APP_NAME + '.apps.reservations.urls')),
    url(r'^zones/', include(MAIN_APP_NAME + '.apps.zones.urls')),
    url(r'^statistics/', include(MAIN_APP_NAME + '.apps.statistics.urls')),
    url(r'^settings/', include(MAIN_APP_NAME + '.apps.administration.urls')),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^', include(MAIN_APP_NAME + '.apps.core.urls')),
]

# Raise errors on purpose
urlpatterns += [
    url(r'^500/$', handler500),
    url(r'^403/$', permission_denied),
    url(r'^404/$', page_not_found),
]

if settings.DEBUG:
    urlpatterns += static_url(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkin_parking/apps/zones/models.py
"""
.. module:: checkin_parking.zones.models
   :synopsis: Checkin Parking Reservation Zone Models.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from django.db.models.base import Model
from django.db.models.fields import PositiveSmallIntegerField, CharField
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.utils.functional import cached_property


class Community(Model):
    """Housing Community."""

    name = CharField(max_length=30, verbose_name="Community Name")

    def __str__(self):
        return self.name


class Building(Model):
    """Housing Building."""

    name = CharField(max_length=30, verbose_name="Building Name")
    community = ForeignKey(Community, verbose_name="Community", related_name="buildings")

    def __str__(self):
        return self.name


class Zone(Model):
    """A Parking zone."""

    name = CharField(max_length=30, unique=True, verbose_name="Name")
    community = ForeignKey(Community, verbose_name="Community")
    buildings = ManyToManyField(Building, verbose_name="Building(s)")
    capacity = PositiveSmallIntegerField(default=30, verbose_name="Capacity")

    @property
    def formatted_building_list(self):
        return ", ".join(self.building_list)

    @cached_property
    def building_list(self):
        return [building.name for building in self.buildings.all().order_by("name")]

    def __str__(self):
        return self.name

checkin_parking/apps/zones/forms.py
"""
.. module:: checkin_parking.zones.forms
   :synopsis: Checkin Parking Reservation Zone Forms.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from clever_selects.form_fields import ModelChoiceField, ChainedModelMultipleChoiceField
from clever_selects.forms import ChainedChoicesModelForm
from django.core.urlresolvers import reverse_lazy

from .models import Zone, Community, Building


class ZoneForm(ChainedChoicesModelForm):
    community = ModelChoiceField(queryset=Community.objects.all())
    buildings = ChainedModelMultipleChoiceField('community', reverse_lazy('zones:chained_building'), Building)

    def __init__(self, *args, **kwargs):
        super(ZoneForm, self).__init__(*args, **kwargs)

        self.fields["name"].error_messages['required'] = 'A zone name is required.'
        self.fields["capacity"].error_messages['required'] = 'A capacity is required.'
        self.fields["community"].error_messages['required'] = 'A community is required.'
        self.fields["buildings"].error_messages['required'] = 'At least one building must be selected.'

        if self.instance and self.instance.id:
            self.fields["capacity"].widget.attrs['readonly'] = True
        self.fields["community"].widget.attrs['autocomplete'] = "off"
        self.fields["buildings"].help_text = ""

    def clean_capacity(self):
        capacity = self.cleaned_data.get("capacity", None)

        if self.instance and self.instance.id:
            return self.instance.capacity
        else:
            return capacity

    class Meta:
        model = Zone
        fields = ['name', 'capacity', 'community', 'buildings']

checkin_parking/apps/zones/views.py
"""
.. module:: checkin_parking.apps.zones.views
   :synopsis: Checkin Parking Reservation Zone Views.

.. moduleauthor:: Alex Kavanaugh <alex@kavdev.io>

"""

from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from clever_selects.views import ChainedSelectFormViewMixin

from .forms import ZoneForm
from .models import Zone


class ZoneListView(ListView):
    template_name = "zones/list_zones.djhtml"
    model = Zone


class ZoneCreateView(ChainedSelectFormViewMixin, CreateView):
    template_name = "zones/create_zone.djhtml"
    form_class = ZoneForm
    model = Zone
    success_url = reverse_lazy('zones:list_zones')


class ZoneUpdateView(ChainedSelectFormViewMixin, UpdateView):
    pk_url_kwarg = 'id'
    template_name = "zones/update_zone.djhtml"
    form_class = ZoneForm
    model = Zone
    success_url = reverse_lazy('zones:list_zones')

checkin_parking/templates/zones/create_zone.html
{% extends "base.html" %}

{% block subtitle %} | Create Zone{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Create a New Zone</h1>
            <p>Use the following form to create a new parking zone. Parking zones are only accessible to residents who live in the community and building(s) designated in the form below.</p>
            <form method="post" id="create_zone_form">
                <fieldset>
                    <legend>
                        New Parking Zone
                    </legend>
                    {{ form.as_p }}
                </fieldset>
                <p>
                    <input type="submit" value="Submit" />
                </p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

checkin_parking/templates/zones/list_zones.html
{% extends "base.html" %}

{% block subtitle %} | Zones{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Parking Zones</h1>
            <p>Parking zones are only accessible to residents who live in the community and building(s) designated in the form below.</p>
            <table border="1" class="table_directory">
                <tbody>
                    <tr>
                        <th>Name</th>
                        <th>Community</th>
                        <th>Building(s)</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    {% for zone in zone_list %}
                    <tr id="zone_{{ zone.id }}">
                        <td>{{ zone.name }}</td>
                        <td>{{ zone.community }}</td>
                        <td>{{ zone.formatted_building_list }}</td>
                        <td><a class="update" href="{% url 'zones:update_zone' id=zone.id %}">Update</a></td>
                        <td><a class="delete" onclick="delete_zone({{ zone.id }}, '{{ zone.name }}')">Delete</a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
{{ block.super }}
<script type="text/javascript">
    function delete_zone(zone_id, zone_name) {
        if (confirm("Are you sure you want to delete '" + zone_name + "'?")) {
            ajaxPost("{% url 'zones:delete_zone' %}", {'zone_id': zone_id}, function(response_context) {
                if (response_context["success"]) {
                    $("#zone_" + zone_id).remove();
                    return true;
                }
            });
        } else {
            return false;
        }
    };
</script>
{% endblock %}

checkin_parking/templates/zones/update_zone.html
{% extends "base.html" %}

{% block subtitle %} | Update Zone{% endblock %}

{% block content %}
    <div id="content">
        <div id="mainLeftFull">
            <h1>Update a Zone</h1>
            <p>Use the following form to update a parking zone. Parking zones are only accessible to residents who live in the community and building(s) designated in the form below.</p>
            <form method="post" id="create_zone_form">
                <fieldset>
                    <legend>
                        Update Parking Zone
                    </legend>
                    {{ form.as_p }}
                </fieldset>
                <p>
                    <input type="submit" value="Submit" />
                </p>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript">
    $(document).ready(function () {
    $("#id_buildings").html("");
        {% if form.buildings.value %}
            ajaxPost("{% url 'zones:ajax_update_building' %}", {'community_id': '{{ form.community.value }}', 'building_selections': '{{ form.buildings.value }}', 'css_target': '#id_buildings'});
        {% endif %}
    });
    
    $("#id_community").change(function () {
        ajaxPost("{% url 'zones:ajax_update_building' %}", {'community_id': $(this).val(), 'css_target': '#id_buildings'});
    });
</script>
{% endblock %}